// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "push_back.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic push_back::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic push_back::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> push_back::ap_ST_fsm_state1 = "1";
const sc_lv<5> push_back::ap_ST_fsm_state2 = "10";
const sc_lv<5> push_back::ap_ST_fsm_state3 = "100";
const sc_lv<5> push_back::ap_ST_fsm_state4 = "1000";
const sc_lv<5> push_back::ap_ST_fsm_state5 = "10000";
const sc_lv<32> push_back::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> push_back::ap_const_lv32_1 = "1";
const sc_lv<32> push_back::ap_const_lv32_2 = "10";
const sc_lv<32> push_back::ap_const_lv32_3 = "11";
const sc_lv<32> push_back::ap_const_lv32_4 = "100";
const sc_lv<3> push_back::ap_const_lv3_0 = "000";
const sc_lv<1> push_back::ap_const_lv1_0 = "0";
const sc_lv<10> push_back::ap_const_lv10_1 = "1";
const sc_lv<10> push_back::ap_const_lv10_2 = "10";
const sc_lv<10> push_back::ap_const_lv10_3 = "11";
const sc_lv<10> push_back::ap_const_lv10_4 = "100";
const sc_lv<10> push_back::ap_const_lv10_5 = "101";
const sc_lv<10> push_back::ap_const_lv10_6 = "110";
const sc_lv<10> push_back::ap_const_lv10_7 = "111";
const sc_lv<10> push_back::ap_const_lv10_8 = "1000";
const sc_lv<10> push_back::ap_const_lv10_9 = "1001";
const bool push_back::ap_const_boolean_1 = true;

push_back::push_back(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_return);
    sensitive << ( mapHLS_unsigned_int_arrayHLS_residData_size_read );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_first_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_fu_1209_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_first_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_first_d0);
    sensitive << ( value_first_read );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_first_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_15_cast_fu_1021_p1 );
    sensitive << ( tmp_17_cast_fu_1070_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_19_cast_fu_1118_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_21_cast_fu_1166_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_23_cast_fu_1219_p1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_16_cast_fu_1036_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_18_cast_fu_1084_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_20_cast_fu_1132_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_22_cast_fu_1180_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_24_cast_fu_1233_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_read22_cast_fu_986_p1 );
    sensitive << ( p_read24_cast_fu_1060_p1 );
    sensitive << ( p_read26_cast_fu_1108_p1 );
    sensitive << ( p_read28_cast_fu_1156_p1 );
    sensitive << ( p_read30_cast_fu_1204_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_read23_cast_fu_981_p1 );
    sensitive << ( p_read25_cast_fu_1055_p1 );
    sensitive << ( p_read27_cast_fu_1103_p1 );
    sensitive << ( p_read29_cast_fu_1151_p1 );
    sensitive << ( p_read31_cast_fu_1199_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_15_cast_fu_1021_p1 );
    sensitive << ( tmp_17_cast_fu_1070_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_19_cast_fu_1118_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_21_cast_fu_1166_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_23_cast_fu_1219_p1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_16_cast_fu_1036_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_18_cast_fu_1084_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_20_cast_fu_1132_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_22_cast_fu_1180_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_24_cast_fu_1233_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read1 );
    sensitive << ( p_read4 );
    sensitive << ( p_read6 );
    sensitive << ( p_read8 );
    sensitive << ( p_read10 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read3 );
    sensitive << ( p_read5 );
    sensitive << ( p_read7 );
    sensitive << ( p_read9 );
    sensitive << ( p_read11 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_15_cast_fu_1021_p1 );
    sensitive << ( tmp_17_cast_fu_1070_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_19_cast_fu_1118_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_21_cast_fu_1166_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_23_cast_fu_1219_p1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_16_cast_fu_1036_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_18_cast_fu_1084_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_20_cast_fu_1132_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_22_cast_fu_1180_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_24_cast_fu_1233_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read42 );
    sensitive << ( p_read44 );
    sensitive << ( p_read46 );
    sensitive << ( p_read48 );
    sensitive << ( p_read50 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read43 );
    sensitive << ( p_read45 );
    sensitive << ( p_read47 );
    sensitive << ( p_read49 );
    sensitive << ( p_read51 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_15_cast_fu_1021_p1 );
    sensitive << ( tmp_17_cast_fu_1070_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_19_cast_fu_1118_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_21_cast_fu_1166_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_23_cast_fu_1219_p1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_16_cast_fu_1036_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_18_cast_fu_1084_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_20_cast_fu_1132_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_22_cast_fu_1180_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_24_cast_fu_1233_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_read32_cast_fu_976_p1 );
    sensitive << ( p_read34_cast_fu_1050_p1 );
    sensitive << ( p_read36_cast_fu_1098_p1 );
    sensitive << ( p_read38_cast_fu_1146_p1 );
    sensitive << ( p_read40_cast_fu_1194_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_read33_cast_fu_971_p1 );
    sensitive << ( p_read35_cast_fu_1045_p1 );
    sensitive << ( p_read37_cast_fu_1093_p1 );
    sensitive << ( p_read39_cast_fu_1141_p1 );
    sensitive << ( p_read41_cast_fu_1189_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_15_cast_fu_1021_p1 );
    sensitive << ( tmp_17_cast_fu_1070_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_19_cast_fu_1118_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_21_cast_fu_1166_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_23_cast_fu_1219_p1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_16_cast_fu_1036_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_18_cast_fu_1084_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_20_cast_fu_1132_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_22_cast_fu_1180_p1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_24_cast_fu_1233_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read12 );
    sensitive << ( p_read14 );
    sensitive << ( p_read16 );
    sensitive << ( p_read18 );
    sensitive << ( p_read20 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_read13 );
    sensitive << ( p_read15 );
    sensitive << ( p_read17 );
    sensitive << ( p_read19 );
    sensitive << ( p_read21 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_fu_1209_p1 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_d0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_p_read22_cast_fu_986_p1);
    sensitive << ( p_read22 );

    SC_METHOD(thread_p_read23_cast_fu_981_p1);
    sensitive << ( p_read23 );

    SC_METHOD(thread_p_read24_cast_fu_1060_p1);
    sensitive << ( p_read24 );

    SC_METHOD(thread_p_read25_cast_fu_1055_p1);
    sensitive << ( p_read25 );

    SC_METHOD(thread_p_read26_cast_fu_1108_p1);
    sensitive << ( p_read26 );

    SC_METHOD(thread_p_read27_cast_fu_1103_p1);
    sensitive << ( p_read27 );

    SC_METHOD(thread_p_read28_cast_fu_1156_p1);
    sensitive << ( p_read28 );

    SC_METHOD(thread_p_read29_cast_fu_1151_p1);
    sensitive << ( p_read29 );

    SC_METHOD(thread_p_read30_cast_fu_1204_p1);
    sensitive << ( p_read30 );

    SC_METHOD(thread_p_read31_cast_fu_1199_p1);
    sensitive << ( p_read31 );

    SC_METHOD(thread_p_read32_cast_fu_976_p1);
    sensitive << ( p_read32 );

    SC_METHOD(thread_p_read33_cast_fu_971_p1);
    sensitive << ( p_read33 );

    SC_METHOD(thread_p_read34_cast_fu_1050_p1);
    sensitive << ( p_read34 );

    SC_METHOD(thread_p_read35_cast_fu_1045_p1);
    sensitive << ( p_read35 );

    SC_METHOD(thread_p_read36_cast_fu_1098_p1);
    sensitive << ( p_read36 );

    SC_METHOD(thread_p_read37_cast_fu_1093_p1);
    sensitive << ( p_read37 );

    SC_METHOD(thread_p_read38_cast_fu_1146_p1);
    sensitive << ( p_read38 );

    SC_METHOD(thread_p_read39_cast_fu_1141_p1);
    sensitive << ( p_read39 );

    SC_METHOD(thread_p_read40_cast_fu_1194_p1);
    sensitive << ( p_read40 );

    SC_METHOD(thread_p_read41_cast_fu_1189_p1);
    sensitive << ( p_read41 );

    SC_METHOD(thread_p_shl1_cast_fu_1007_p3);
    sensitive << ( tmp_4_fu_1003_p1 );

    SC_METHOD(thread_p_shl_cast_fu_995_p3);
    sensitive << ( tmp_3_fu_991_p1 );

    SC_METHOD(thread_tmp_12_fu_1030_p2);
    sensitive << ( tmp_s_fu_1015_p2 );

    SC_METHOD(thread_tmp_13_fu_1065_p2);
    sensitive << ( tmp_s_reg_1253 );

    SC_METHOD(thread_tmp_14_fu_1079_p2);
    sensitive << ( tmp_s_reg_1253 );

    SC_METHOD(thread_tmp_15_cast_fu_1021_p1);
    sensitive << ( tmp_s_fu_1015_p2 );

    SC_METHOD(thread_tmp_15_fu_1113_p2);
    sensitive << ( tmp_s_reg_1253 );

    SC_METHOD(thread_tmp_16_cast_fu_1036_p1);
    sensitive << ( tmp_12_fu_1030_p2 );

    SC_METHOD(thread_tmp_16_fu_1127_p2);
    sensitive << ( tmp_s_reg_1253 );

    SC_METHOD(thread_tmp_17_cast_fu_1070_p1);
    sensitive << ( tmp_13_fu_1065_p2 );

    SC_METHOD(thread_tmp_17_fu_1161_p2);
    sensitive << ( tmp_s_reg_1253 );

    SC_METHOD(thread_tmp_18_cast_fu_1084_p1);
    sensitive << ( tmp_14_fu_1079_p2 );

    SC_METHOD(thread_tmp_18_fu_1175_p2);
    sensitive << ( tmp_s_reg_1253 );

    SC_METHOD(thread_tmp_19_cast_fu_1118_p1);
    sensitive << ( tmp_15_fu_1113_p2 );

    SC_METHOD(thread_tmp_19_fu_1214_p2);
    sensitive << ( tmp_s_reg_1253 );

    SC_METHOD(thread_tmp_20_cast_fu_1132_p1);
    sensitive << ( tmp_16_fu_1127_p2 );

    SC_METHOD(thread_tmp_20_fu_1228_p2);
    sensitive << ( tmp_s_reg_1253 );

    SC_METHOD(thread_tmp_21_cast_fu_1166_p1);
    sensitive << ( tmp_17_fu_1161_p2 );

    SC_METHOD(thread_tmp_22_cast_fu_1180_p1);
    sensitive << ( tmp_18_fu_1175_p2 );

    SC_METHOD(thread_tmp_23_cast_fu_1219_p1);
    sensitive << ( tmp_19_fu_1214_p2 );

    SC_METHOD(thread_tmp_24_cast_fu_1233_p1);
    sensitive << ( tmp_20_fu_1228_p2 );

    SC_METHOD(thread_tmp_3_fu_991_p1);
    sensitive << ( mapHLS_unsigned_int_arrayHLS_residData_size_read );

    SC_METHOD(thread_tmp_4_fu_1003_p1);
    sensitive << ( mapHLS_unsigned_int_arrayHLS_residData_size_read );

    SC_METHOD(thread_tmp_fu_1209_p1);
    sensitive << ( mapHLS_unsigned_int_arrayHLS_residData_size_read );

    SC_METHOD(thread_tmp_s_fu_1015_p2);
    sensitive << ( p_shl_cast_fu_995_p3 );
    sensitive << ( p_shl1_cast_fu_1007_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    ap_CS_fsm = "00001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "push_back_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_size_read, "(port)mapHLS_unsigned_int_arrayHLS_residData_size_read");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_first_address0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_first_address0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_first_ce0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_first_ce0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_first_we0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_first_we0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_first_d0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_first_d0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_address0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_address0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_ce0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_ce0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_we0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_we0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_d0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_d0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we1");
    sc_trace(mVcdFile, mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1, "(port)mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1");
    sc_trace(mVcdFile, value_first_read, "(port)value_first_read");
    sc_trace(mVcdFile, p_read1, "(port)p_read1");
    sc_trace(mVcdFile, p_read3, "(port)p_read3");
    sc_trace(mVcdFile, p_read4, "(port)p_read4");
    sc_trace(mVcdFile, p_read5, "(port)p_read5");
    sc_trace(mVcdFile, p_read6, "(port)p_read6");
    sc_trace(mVcdFile, p_read7, "(port)p_read7");
    sc_trace(mVcdFile, p_read8, "(port)p_read8");
    sc_trace(mVcdFile, p_read9, "(port)p_read9");
    sc_trace(mVcdFile, p_read10, "(port)p_read10");
    sc_trace(mVcdFile, p_read11, "(port)p_read11");
    sc_trace(mVcdFile, p_read12, "(port)p_read12");
    sc_trace(mVcdFile, p_read13, "(port)p_read13");
    sc_trace(mVcdFile, p_read14, "(port)p_read14");
    sc_trace(mVcdFile, p_read15, "(port)p_read15");
    sc_trace(mVcdFile, p_read16, "(port)p_read16");
    sc_trace(mVcdFile, p_read17, "(port)p_read17");
    sc_trace(mVcdFile, p_read18, "(port)p_read18");
    sc_trace(mVcdFile, p_read19, "(port)p_read19");
    sc_trace(mVcdFile, p_read20, "(port)p_read20");
    sc_trace(mVcdFile, p_read21, "(port)p_read21");
    sc_trace(mVcdFile, p_read22, "(port)p_read22");
    sc_trace(mVcdFile, p_read23, "(port)p_read23");
    sc_trace(mVcdFile, p_read24, "(port)p_read24");
    sc_trace(mVcdFile, p_read25, "(port)p_read25");
    sc_trace(mVcdFile, p_read26, "(port)p_read26");
    sc_trace(mVcdFile, p_read27, "(port)p_read27");
    sc_trace(mVcdFile, p_read28, "(port)p_read28");
    sc_trace(mVcdFile, p_read29, "(port)p_read29");
    sc_trace(mVcdFile, p_read30, "(port)p_read30");
    sc_trace(mVcdFile, p_read31, "(port)p_read31");
    sc_trace(mVcdFile, p_read32, "(port)p_read32");
    sc_trace(mVcdFile, p_read33, "(port)p_read33");
    sc_trace(mVcdFile, p_read34, "(port)p_read34");
    sc_trace(mVcdFile, p_read35, "(port)p_read35");
    sc_trace(mVcdFile, p_read36, "(port)p_read36");
    sc_trace(mVcdFile, p_read37, "(port)p_read37");
    sc_trace(mVcdFile, p_read38, "(port)p_read38");
    sc_trace(mVcdFile, p_read39, "(port)p_read39");
    sc_trace(mVcdFile, p_read40, "(port)p_read40");
    sc_trace(mVcdFile, p_read41, "(port)p_read41");
    sc_trace(mVcdFile, p_read42, "(port)p_read42");
    sc_trace(mVcdFile, p_read43, "(port)p_read43");
    sc_trace(mVcdFile, p_read44, "(port)p_read44");
    sc_trace(mVcdFile, p_read45, "(port)p_read45");
    sc_trace(mVcdFile, p_read46, "(port)p_read46");
    sc_trace(mVcdFile, p_read47, "(port)p_read47");
    sc_trace(mVcdFile, p_read48, "(port)p_read48");
    sc_trace(mVcdFile, p_read49, "(port)p_read49");
    sc_trace(mVcdFile, p_read50, "(port)p_read50");
    sc_trace(mVcdFile, p_read51, "(port)p_read51");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_s_fu_1015_p2, "tmp_s_fu_1015_p2");
    sc_trace(mVcdFile, tmp_s_reg_1253, "tmp_s_reg_1253");
    sc_trace(mVcdFile, tmp_15_cast_fu_1021_p1, "tmp_15_cast_fu_1021_p1");
    sc_trace(mVcdFile, tmp_16_cast_fu_1036_p1, "tmp_16_cast_fu_1036_p1");
    sc_trace(mVcdFile, tmp_17_cast_fu_1070_p1, "tmp_17_cast_fu_1070_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_18_cast_fu_1084_p1, "tmp_18_cast_fu_1084_p1");
    sc_trace(mVcdFile, tmp_19_cast_fu_1118_p1, "tmp_19_cast_fu_1118_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_20_cast_fu_1132_p1, "tmp_20_cast_fu_1132_p1");
    sc_trace(mVcdFile, tmp_21_cast_fu_1166_p1, "tmp_21_cast_fu_1166_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_22_cast_fu_1180_p1, "tmp_22_cast_fu_1180_p1");
    sc_trace(mVcdFile, tmp_23_cast_fu_1219_p1, "tmp_23_cast_fu_1219_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_24_cast_fu_1233_p1, "tmp_24_cast_fu_1233_p1");
    sc_trace(mVcdFile, tmp_fu_1209_p1, "tmp_fu_1209_p1");
    sc_trace(mVcdFile, p_read22_cast_fu_986_p1, "p_read22_cast_fu_986_p1");
    sc_trace(mVcdFile, p_read23_cast_fu_981_p1, "p_read23_cast_fu_981_p1");
    sc_trace(mVcdFile, p_read24_cast_fu_1060_p1, "p_read24_cast_fu_1060_p1");
    sc_trace(mVcdFile, p_read25_cast_fu_1055_p1, "p_read25_cast_fu_1055_p1");
    sc_trace(mVcdFile, p_read26_cast_fu_1108_p1, "p_read26_cast_fu_1108_p1");
    sc_trace(mVcdFile, p_read27_cast_fu_1103_p1, "p_read27_cast_fu_1103_p1");
    sc_trace(mVcdFile, p_read28_cast_fu_1156_p1, "p_read28_cast_fu_1156_p1");
    sc_trace(mVcdFile, p_read29_cast_fu_1151_p1, "p_read29_cast_fu_1151_p1");
    sc_trace(mVcdFile, p_read30_cast_fu_1204_p1, "p_read30_cast_fu_1204_p1");
    sc_trace(mVcdFile, p_read31_cast_fu_1199_p1, "p_read31_cast_fu_1199_p1");
    sc_trace(mVcdFile, p_read32_cast_fu_976_p1, "p_read32_cast_fu_976_p1");
    sc_trace(mVcdFile, p_read33_cast_fu_971_p1, "p_read33_cast_fu_971_p1");
    sc_trace(mVcdFile, p_read34_cast_fu_1050_p1, "p_read34_cast_fu_1050_p1");
    sc_trace(mVcdFile, p_read35_cast_fu_1045_p1, "p_read35_cast_fu_1045_p1");
    sc_trace(mVcdFile, p_read36_cast_fu_1098_p1, "p_read36_cast_fu_1098_p1");
    sc_trace(mVcdFile, p_read37_cast_fu_1093_p1, "p_read37_cast_fu_1093_p1");
    sc_trace(mVcdFile, p_read38_cast_fu_1146_p1, "p_read38_cast_fu_1146_p1");
    sc_trace(mVcdFile, p_read39_cast_fu_1141_p1, "p_read39_cast_fu_1141_p1");
    sc_trace(mVcdFile, p_read40_cast_fu_1194_p1, "p_read40_cast_fu_1194_p1");
    sc_trace(mVcdFile, p_read41_cast_fu_1189_p1, "p_read41_cast_fu_1189_p1");
    sc_trace(mVcdFile, tmp_3_fu_991_p1, "tmp_3_fu_991_p1");
    sc_trace(mVcdFile, tmp_4_fu_1003_p1, "tmp_4_fu_1003_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_995_p3, "p_shl_cast_fu_995_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_1007_p3, "p_shl1_cast_fu_1007_p3");
    sc_trace(mVcdFile, tmp_12_fu_1030_p2, "tmp_12_fu_1030_p2");
    sc_trace(mVcdFile, tmp_13_fu_1065_p2, "tmp_13_fu_1065_p2");
    sc_trace(mVcdFile, tmp_14_fu_1079_p2, "tmp_14_fu_1079_p2");
    sc_trace(mVcdFile, tmp_15_fu_1113_p2, "tmp_15_fu_1113_p2");
    sc_trace(mVcdFile, tmp_16_fu_1127_p2, "tmp_16_fu_1127_p2");
    sc_trace(mVcdFile, tmp_17_fu_1161_p2, "tmp_17_fu_1161_p2");
    sc_trace(mVcdFile, tmp_18_fu_1175_p2, "tmp_18_fu_1175_p2");
    sc_trace(mVcdFile, tmp_19_fu_1214_p2, "tmp_19_fu_1214_p2");
    sc_trace(mVcdFile, tmp_20_fu_1228_p2, "tmp_20_fu_1228_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

push_back::~push_back() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void push_back::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_s_reg_1253 = tmp_s_fu_1015_p2.read();
    }
}

void push_back::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void push_back::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void push_back::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void push_back::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void push_back::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void push_back::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void push_back::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void push_back::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void push_back::thread_ap_return() {
    ap_return = (!ap_const_lv32_1.is_01() || !mapHLS_unsigned_int_arrayHLS_residData_size_read.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(mapHLS_unsigned_int_arrayHLS_residData_size_read.read()));
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_first_address0() {
    mapHLS_unsigned_int_arrayHLS_residData_data_first_address0 =  (sc_lv<5>) (tmp_fu_1209_p1.read());
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_first_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_first_ce0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_first_ce0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_first_d0() {
    mapHLS_unsigned_int_arrayHLS_residData_data_first_d0 = value_first_read.read();
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_first_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_first_we0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_first_we0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 =  (sc_lv<9>) (tmp_23_cast_fu_1219_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 =  (sc_lv<9>) (tmp_21_cast_fu_1166_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 =  (sc_lv<9>) (tmp_19_cast_fu_1118_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 =  (sc_lv<9>) (tmp_17_cast_fu_1070_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 =  (sc_lv<9>) (tmp_15_cast_fu_1021_p1.read());
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 = "XXXXXXXXX";
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 =  (sc_lv<9>) (tmp_24_cast_fu_1233_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 =  (sc_lv<9>) (tmp_22_cast_fu_1180_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 =  (sc_lv<9>) (tmp_20_cast_fu_1132_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 =  (sc_lv<9>) (tmp_18_cast_fu_1084_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 =  (sc_lv<9>) (tmp_16_cast_fu_1036_p1.read());
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 = "XXXXXXXXX";
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce1 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce1 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 = p_read30_cast_fu_1204_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 = p_read28_cast_fu_1156_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 = p_read26_cast_fu_1108_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 = p_read24_cast_fu_1060_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 = p_read22_cast_fu_986_p1.read();
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 = p_read31_cast_fu_1199_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 = p_read29_cast_fu_1151_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 = p_read27_cast_fu_1103_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 = p_read25_cast_fu_1055_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 = p_read23_cast_fu_981_p1.read();
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we1 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we1 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 =  (sc_lv<9>) (tmp_23_cast_fu_1219_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 =  (sc_lv<9>) (tmp_21_cast_fu_1166_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 =  (sc_lv<9>) (tmp_19_cast_fu_1118_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 =  (sc_lv<9>) (tmp_17_cast_fu_1070_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 =  (sc_lv<9>) (tmp_15_cast_fu_1021_p1.read());
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 = "XXXXXXXXX";
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 =  (sc_lv<9>) (tmp_24_cast_fu_1233_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 =  (sc_lv<9>) (tmp_22_cast_fu_1180_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 =  (sc_lv<9>) (tmp_20_cast_fu_1132_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 =  (sc_lv<9>) (tmp_18_cast_fu_1084_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 =  (sc_lv<9>) (tmp_16_cast_fu_1036_p1.read());
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 = "XXXXXXXXX";
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce1 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce1 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 = p_read10.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 = p_read8.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 = p_read6.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 = p_read4.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 = p_read1.read();
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 = p_read11.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 = p_read9.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 = p_read7.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 = p_read5.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 = p_read3.read();
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we1 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we1 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 =  (sc_lv<9>) (tmp_23_cast_fu_1219_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 =  (sc_lv<9>) (tmp_21_cast_fu_1166_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 =  (sc_lv<9>) (tmp_19_cast_fu_1118_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 =  (sc_lv<9>) (tmp_17_cast_fu_1070_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 =  (sc_lv<9>) (tmp_15_cast_fu_1021_p1.read());
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 = "XXXXXXXXX";
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 =  (sc_lv<9>) (tmp_24_cast_fu_1233_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 =  (sc_lv<9>) (tmp_22_cast_fu_1180_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 =  (sc_lv<9>) (tmp_20_cast_fu_1132_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 =  (sc_lv<9>) (tmp_18_cast_fu_1084_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 =  (sc_lv<9>) (tmp_16_cast_fu_1036_p1.read());
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 = "XXXXXXXXX";
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce1 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce1 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 = p_read50.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 = p_read48.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 = p_read46.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 = p_read44.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 = p_read42.read();
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 =  (sc_lv<1>) ("X");
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 = p_read51.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 = p_read49.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 = p_read47.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 = p_read45.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 = p_read43.read();
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 =  (sc_lv<1>) ("X");
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we1 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we1 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 =  (sc_lv<9>) (tmp_23_cast_fu_1219_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 =  (sc_lv<9>) (tmp_21_cast_fu_1166_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 =  (sc_lv<9>) (tmp_19_cast_fu_1118_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 =  (sc_lv<9>) (tmp_17_cast_fu_1070_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 =  (sc_lv<9>) (tmp_15_cast_fu_1021_p1.read());
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 = "XXXXXXXXX";
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 =  (sc_lv<9>) (tmp_24_cast_fu_1233_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 =  (sc_lv<9>) (tmp_22_cast_fu_1180_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 =  (sc_lv<9>) (tmp_20_cast_fu_1132_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 =  (sc_lv<9>) (tmp_18_cast_fu_1084_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 =  (sc_lv<9>) (tmp_16_cast_fu_1036_p1.read());
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 = "XXXXXXXXX";
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce1 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce1 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 = p_read40_cast_fu_1194_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 = p_read38_cast_fu_1146_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 = p_read36_cast_fu_1098_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 = p_read34_cast_fu_1050_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 = p_read32_cast_fu_976_p1.read();
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 = p_read41_cast_fu_1189_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 = p_read39_cast_fu_1141_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 = p_read37_cast_fu_1093_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 = p_read35_cast_fu_1045_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 = p_read33_cast_fu_971_p1.read();
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we1 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we1 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 =  (sc_lv<9>) (tmp_23_cast_fu_1219_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 =  (sc_lv<9>) (tmp_21_cast_fu_1166_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 =  (sc_lv<9>) (tmp_19_cast_fu_1118_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 =  (sc_lv<9>) (tmp_17_cast_fu_1070_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 =  (sc_lv<9>) (tmp_15_cast_fu_1021_p1.read());
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 = "XXXXXXXXX";
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 =  (sc_lv<9>) (tmp_24_cast_fu_1233_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 =  (sc_lv<9>) (tmp_22_cast_fu_1180_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 =  (sc_lv<9>) (tmp_20_cast_fu_1132_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 =  (sc_lv<9>) (tmp_18_cast_fu_1084_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 =  (sc_lv<9>) (tmp_16_cast_fu_1036_p1.read());
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 = "XXXXXXXXX";
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce1 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce1 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 = p_read20.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 = p_read18.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 = p_read16.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 = p_read14.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 = p_read12.read();
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 = p_read21.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 = p_read19.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 = p_read17.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 = p_read15.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 = p_read13.read();
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we1 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we1 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_address0() {
    mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_address0 =  (sc_lv<5>) (tmp_fu_1209_p1.read());
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_ce0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_ce0 = ap_const_logic_0;
    }
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_d0() {
    mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_d0 = ap_const_lv32_0;
}

void push_back::thread_mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_we0 = ap_const_logic_1;
    } else {
        mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_we0 = ap_const_logic_0;
    }
}

void push_back::thread_p_read22_cast_fu_986_p1() {
    p_read22_cast_fu_986_p1 = esl_zext<32,1>(p_read22.read());
}

void push_back::thread_p_read23_cast_fu_981_p1() {
    p_read23_cast_fu_981_p1 = esl_zext<32,1>(p_read23.read());
}

void push_back::thread_p_read24_cast_fu_1060_p1() {
    p_read24_cast_fu_1060_p1 = esl_zext<32,1>(p_read24.read());
}

void push_back::thread_p_read25_cast_fu_1055_p1() {
    p_read25_cast_fu_1055_p1 = esl_zext<32,1>(p_read25.read());
}

void push_back::thread_p_read26_cast_fu_1108_p1() {
    p_read26_cast_fu_1108_p1 = esl_zext<32,1>(p_read26.read());
}

void push_back::thread_p_read27_cast_fu_1103_p1() {
    p_read27_cast_fu_1103_p1 = esl_zext<32,1>(p_read27.read());
}

void push_back::thread_p_read28_cast_fu_1156_p1() {
    p_read28_cast_fu_1156_p1 = esl_zext<32,1>(p_read28.read());
}

void push_back::thread_p_read29_cast_fu_1151_p1() {
    p_read29_cast_fu_1151_p1 = esl_zext<32,1>(p_read29.read());
}

void push_back::thread_p_read30_cast_fu_1204_p1() {
    p_read30_cast_fu_1204_p1 = esl_zext<32,1>(p_read30.read());
}

void push_back::thread_p_read31_cast_fu_1199_p1() {
    p_read31_cast_fu_1199_p1 = esl_zext<32,1>(p_read31.read());
}

void push_back::thread_p_read32_cast_fu_976_p1() {
    p_read32_cast_fu_976_p1 = esl_zext<32,1>(p_read32.read());
}

void push_back::thread_p_read33_cast_fu_971_p1() {
    p_read33_cast_fu_971_p1 = esl_zext<32,1>(p_read33.read());
}

void push_back::thread_p_read34_cast_fu_1050_p1() {
    p_read34_cast_fu_1050_p1 = esl_zext<32,1>(p_read34.read());
}

void push_back::thread_p_read35_cast_fu_1045_p1() {
    p_read35_cast_fu_1045_p1 = esl_zext<32,1>(p_read35.read());
}

void push_back::thread_p_read36_cast_fu_1098_p1() {
    p_read36_cast_fu_1098_p1 = esl_zext<32,1>(p_read36.read());
}

void push_back::thread_p_read37_cast_fu_1093_p1() {
    p_read37_cast_fu_1093_p1 = esl_zext<32,1>(p_read37.read());
}

void push_back::thread_p_read38_cast_fu_1146_p1() {
    p_read38_cast_fu_1146_p1 = esl_zext<32,1>(p_read38.read());
}

void push_back::thread_p_read39_cast_fu_1141_p1() {
    p_read39_cast_fu_1141_p1 = esl_zext<32,1>(p_read39.read());
}

void push_back::thread_p_read40_cast_fu_1194_p1() {
    p_read40_cast_fu_1194_p1 = esl_zext<32,1>(p_read40.read());
}

void push_back::thread_p_read41_cast_fu_1189_p1() {
    p_read41_cast_fu_1189_p1 = esl_zext<32,1>(p_read41.read());
}

void push_back::thread_p_shl1_cast_fu_1007_p3() {
    p_shl1_cast_fu_1007_p3 = esl_concat<9,1>(tmp_4_fu_1003_p1.read(), ap_const_lv1_0);
}

void push_back::thread_p_shl_cast_fu_995_p3() {
    p_shl_cast_fu_995_p3 = esl_concat<7,3>(tmp_3_fu_991_p1.read(), ap_const_lv3_0);
}

void push_back::thread_tmp_12_fu_1030_p2() {
    tmp_12_fu_1030_p2 = (tmp_s_fu_1015_p2.read() | ap_const_lv10_1);
}

void push_back::thread_tmp_13_fu_1065_p2() {
    tmp_13_fu_1065_p2 = (!ap_const_lv10_2.is_01() || !tmp_s_reg_1253.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_2) + sc_biguint<10>(tmp_s_reg_1253.read()));
}

void push_back::thread_tmp_14_fu_1079_p2() {
    tmp_14_fu_1079_p2 = (!ap_const_lv10_3.is_01() || !tmp_s_reg_1253.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_3) + sc_biguint<10>(tmp_s_reg_1253.read()));
}

void push_back::thread_tmp_15_cast_fu_1021_p1() {
    tmp_15_cast_fu_1021_p1 = esl_zext<64,10>(tmp_s_fu_1015_p2.read());
}

void push_back::thread_tmp_15_fu_1113_p2() {
    tmp_15_fu_1113_p2 = (!ap_const_lv10_4.is_01() || !tmp_s_reg_1253.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_4) + sc_biguint<10>(tmp_s_reg_1253.read()));
}

void push_back::thread_tmp_16_cast_fu_1036_p1() {
    tmp_16_cast_fu_1036_p1 = esl_zext<64,10>(tmp_12_fu_1030_p2.read());
}

void push_back::thread_tmp_16_fu_1127_p2() {
    tmp_16_fu_1127_p2 = (!ap_const_lv10_5.is_01() || !tmp_s_reg_1253.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_5) + sc_biguint<10>(tmp_s_reg_1253.read()));
}

void push_back::thread_tmp_17_cast_fu_1070_p1() {
    tmp_17_cast_fu_1070_p1 = esl_sext<64,10>(tmp_13_fu_1065_p2.read());
}

void push_back::thread_tmp_17_fu_1161_p2() {
    tmp_17_fu_1161_p2 = (!ap_const_lv10_6.is_01() || !tmp_s_reg_1253.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_6) + sc_biguint<10>(tmp_s_reg_1253.read()));
}

void push_back::thread_tmp_18_cast_fu_1084_p1() {
    tmp_18_cast_fu_1084_p1 = esl_sext<64,10>(tmp_14_fu_1079_p2.read());
}

void push_back::thread_tmp_18_fu_1175_p2() {
    tmp_18_fu_1175_p2 = (!ap_const_lv10_7.is_01() || !tmp_s_reg_1253.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_7) + sc_biguint<10>(tmp_s_reg_1253.read()));
}

void push_back::thread_tmp_19_cast_fu_1118_p1() {
    tmp_19_cast_fu_1118_p1 = esl_sext<64,10>(tmp_15_fu_1113_p2.read());
}

void push_back::thread_tmp_19_fu_1214_p2() {
    tmp_19_fu_1214_p2 = (!ap_const_lv10_8.is_01() || !tmp_s_reg_1253.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_8) + sc_biguint<10>(tmp_s_reg_1253.read()));
}

void push_back::thread_tmp_20_cast_fu_1132_p1() {
    tmp_20_cast_fu_1132_p1 = esl_sext<64,10>(tmp_16_fu_1127_p2.read());
}

void push_back::thread_tmp_20_fu_1228_p2() {
    tmp_20_fu_1228_p2 = (!ap_const_lv10_9.is_01() || !tmp_s_reg_1253.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_9) + sc_biguint<10>(tmp_s_reg_1253.read()));
}

void push_back::thread_tmp_21_cast_fu_1166_p1() {
    tmp_21_cast_fu_1166_p1 = esl_sext<64,10>(tmp_17_fu_1161_p2.read());
}

void push_back::thread_tmp_22_cast_fu_1180_p1() {
    tmp_22_cast_fu_1180_p1 = esl_sext<64,10>(tmp_18_fu_1175_p2.read());
}

void push_back::thread_tmp_23_cast_fu_1219_p1() {
    tmp_23_cast_fu_1219_p1 = esl_sext<64,10>(tmp_19_fu_1214_p2.read());
}

void push_back::thread_tmp_24_cast_fu_1233_p1() {
    tmp_24_cast_fu_1233_p1 = esl_sext<64,10>(tmp_20_fu_1228_p2.read());
}

void push_back::thread_tmp_3_fu_991_p1() {
    tmp_3_fu_991_p1 = mapHLS_unsigned_int_arrayHLS_residData_size_read.read().range(7-1, 0);
}

void push_back::thread_tmp_4_fu_1003_p1() {
    tmp_4_fu_1003_p1 = mapHLS_unsigned_int_arrayHLS_residData_size_read.read().range(9-1, 0);
}

void push_back::thread_tmp_fu_1209_p1() {
    tmp_fu_1209_p1 = esl_zext<64,32>(mapHLS_unsigned_int_arrayHLS_residData_size_read.read());
}

void push_back::thread_tmp_s_fu_1015_p2() {
    tmp_s_fu_1015_p2 = (!p_shl_cast_fu_995_p3.read().is_01() || !p_shl1_cast_fu_1007_p3.read().is_01())? sc_lv<10>(): (sc_biguint<10>(p_shl_cast_fu_995_p3.read()) + sc_biguint<10>(p_shl1_cast_fu_1007_p3.read()));
}

void push_back::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

