-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity push_back is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_size_read : IN STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_first_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_first_ce0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_first_we0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_first_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_ce0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_we0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce1 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we1 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce1 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we1 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce1 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we1 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce1 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we1 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we0 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce1 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we1 : OUT STD_LOGIC;
    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    value_first_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read20 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read21 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read23 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read32 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read33 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read34 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read35 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read36 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read37 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read38 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read39 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read40 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read41 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read42 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read43 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read44 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read45 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read46 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read47 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read48 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read49 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read50 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_read51 : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of push_back is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_const_lv10_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000011";
    constant ap_const_lv10_4 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_const_lv10_5 : STD_LOGIC_VECTOR (9 downto 0) := "0000000101";
    constant ap_const_lv10_6 : STD_LOGIC_VECTOR (9 downto 0) := "0000000110";
    constant ap_const_lv10_7 : STD_LOGIC_VECTOR (9 downto 0) := "0000000111";
    constant ap_const_lv10_8 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_const_lv10_9 : STD_LOGIC_VECTOR (9 downto 0) := "0000001001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_s_fu_1015_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_reg_1253 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_15_cast_fu_1021_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_16_cast_fu_1036_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_17_cast_fu_1070_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_18_cast_fu_1084_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_19_cast_fu_1118_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_20_cast_fu_1132_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_21_cast_fu_1166_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_22_cast_fu_1180_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_23_cast_fu_1219_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_24_cast_fu_1233_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_1209_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_read22_cast_fu_986_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read23_cast_fu_981_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read24_cast_fu_1060_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read25_cast_fu_1055_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read26_cast_fu_1108_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read27_cast_fu_1103_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read28_cast_fu_1156_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read29_cast_fu_1151_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read30_cast_fu_1204_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read31_cast_fu_1199_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read32_cast_fu_976_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read33_cast_fu_971_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read34_cast_fu_1050_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read35_cast_fu_1045_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read36_cast_fu_1098_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read37_cast_fu_1093_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read38_cast_fu_1146_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read39_cast_fu_1141_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read40_cast_fu_1194_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read41_cast_fu_1189_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_991_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_4_fu_1003_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_cast_fu_995_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl1_cast_fu_1007_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_12_fu_1030_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_13_fu_1065_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_14_fu_1079_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_15_fu_1113_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_16_fu_1127_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_17_fu_1161_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_18_fu_1175_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_19_fu_1214_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_20_fu_1228_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    tmp_s_reg_1253(9 downto 1) <= tmp_s_fu_1015_p2(9 downto 1);
            end if;
        end if;
    end process;
    tmp_s_reg_1253(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(mapHLS_unsigned_int_arrayHLS_residData_size_read));
    mapHLS_unsigned_int_arrayHLS_residData_data_first_address0 <= tmp_fu_1209_p1(5 - 1 downto 0);

    mapHLS_unsigned_int_arrayHLS_residData_data_first_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_first_ce0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_first_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mapHLS_unsigned_int_arrayHLS_residData_data_first_d0 <= value_first_read;

    mapHLS_unsigned_int_arrayHLS_residData_data_first_we0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_first_we0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_first_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0_assign_proc : process(ap_CS_fsm_state1, tmp_15_cast_fu_1021_p1, tmp_17_cast_fu_1070_p1, ap_CS_fsm_state2, tmp_19_cast_fu_1118_p1, ap_CS_fsm_state3, tmp_21_cast_fu_1166_p1, ap_CS_fsm_state4, tmp_23_cast_fu_1219_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 <= tmp_23_cast_fu_1219_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 <= tmp_21_cast_fu_1166_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 <= tmp_19_cast_fu_1118_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 <= tmp_17_cast_fu_1070_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 <= tmp_15_cast_fu_1021_p1(9 - 1 downto 0);
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1_assign_proc : process(ap_CS_fsm_state1, tmp_16_cast_fu_1036_p1, ap_CS_fsm_state2, tmp_18_cast_fu_1084_p1, ap_CS_fsm_state3, tmp_20_cast_fu_1132_p1, ap_CS_fsm_state4, tmp_22_cast_fu_1180_p1, ap_CS_fsm_state5, tmp_24_cast_fu_1233_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 <= tmp_24_cast_fu_1233_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 <= tmp_22_cast_fu_1180_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 <= tmp_20_cast_fu_1132_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 <= tmp_18_cast_fu_1084_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 <= tmp_16_cast_fu_1036_p1(9 - 1 downto 0);
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce1 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, p_read22_cast_fu_986_p1, p_read24_cast_fu_1060_p1, p_read26_cast_fu_1108_p1, p_read28_cast_fu_1156_p1, p_read30_cast_fu_1204_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 <= p_read30_cast_fu_1204_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 <= p_read28_cast_fu_1156_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 <= p_read26_cast_fu_1108_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 <= p_read24_cast_fu_1060_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 <= p_read22_cast_fu_986_p1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, p_read23_cast_fu_981_p1, p_read25_cast_fu_1055_p1, p_read27_cast_fu_1103_p1, p_read29_cast_fu_1151_p1, p_read31_cast_fu_1199_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 <= p_read31_cast_fu_1199_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 <= p_read29_cast_fu_1151_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 <= p_read27_cast_fu_1103_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 <= p_read25_cast_fu_1055_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 <= p_read23_cast_fu_981_p1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we1 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_layerId_we1 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0_assign_proc : process(ap_CS_fsm_state1, tmp_15_cast_fu_1021_p1, tmp_17_cast_fu_1070_p1, ap_CS_fsm_state2, tmp_19_cast_fu_1118_p1, ap_CS_fsm_state3, tmp_21_cast_fu_1166_p1, ap_CS_fsm_state4, tmp_23_cast_fu_1219_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 <= tmp_23_cast_fu_1219_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 <= tmp_21_cast_fu_1166_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 <= tmp_19_cast_fu_1118_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 <= tmp_17_cast_fu_1070_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 <= tmp_15_cast_fu_1021_p1(9 - 1 downto 0);
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1_assign_proc : process(ap_CS_fsm_state1, tmp_16_cast_fu_1036_p1, ap_CS_fsm_state2, tmp_18_cast_fu_1084_p1, ap_CS_fsm_state3, tmp_20_cast_fu_1132_p1, ap_CS_fsm_state4, tmp_22_cast_fu_1180_p1, ap_CS_fsm_state5, tmp_24_cast_fu_1233_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 <= tmp_24_cast_fu_1233_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 <= tmp_22_cast_fu_1180_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 <= tmp_20_cast_fu_1132_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 <= tmp_18_cast_fu_1084_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 <= tmp_16_cast_fu_1036_p1(9 - 1 downto 0);
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce1 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0_assign_proc : process(ap_CS_fsm_state1, p_read1, p_read4, p_read6, p_read8, p_read10, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 <= p_read10;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 <= p_read8;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 <= p_read6;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 <= p_read4;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 <= p_read1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1_assign_proc : process(ap_CS_fsm_state1, p_read3, p_read5, p_read7, p_read9, p_read11, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 <= p_read11;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 <= p_read9;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 <= p_read7;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 <= p_read5;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 <= p_read3;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we1 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_phi_we1 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0_assign_proc : process(ap_CS_fsm_state1, tmp_15_cast_fu_1021_p1, tmp_17_cast_fu_1070_p1, ap_CS_fsm_state2, tmp_19_cast_fu_1118_p1, ap_CS_fsm_state3, tmp_21_cast_fu_1166_p1, ap_CS_fsm_state4, tmp_23_cast_fu_1219_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 <= tmp_23_cast_fu_1219_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 <= tmp_21_cast_fu_1166_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 <= tmp_19_cast_fu_1118_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 <= tmp_17_cast_fu_1070_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 <= tmp_15_cast_fu_1021_p1(9 - 1 downto 0);
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1_assign_proc : process(ap_CS_fsm_state1, tmp_16_cast_fu_1036_p1, ap_CS_fsm_state2, tmp_18_cast_fu_1084_p1, ap_CS_fsm_state3, tmp_20_cast_fu_1132_p1, ap_CS_fsm_state4, tmp_22_cast_fu_1180_p1, ap_CS_fsm_state5, tmp_24_cast_fu_1233_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 <= tmp_24_cast_fu_1233_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 <= tmp_22_cast_fu_1180_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 <= tmp_20_cast_fu_1132_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 <= tmp_18_cast_fu_1084_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 <= tmp_16_cast_fu_1036_p1(9 - 1 downto 0);
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce1 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0_assign_proc : process(ap_CS_fsm_state1, p_read42, p_read44, p_read46, p_read48, p_read50, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 <= p_read50;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 <= p_read48;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 <= p_read46;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 <= p_read44;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 <= p_read42;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d0 <= "X";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1_assign_proc : process(ap_CS_fsm_state1, p_read43, p_read45, p_read47, p_read49, p_read51, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 <= p_read51;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 <= p_read49;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 <= p_read47;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 <= p_read45;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 <= p_read43;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_d1 <= "X";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we1 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_ps_we1 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0_assign_proc : process(ap_CS_fsm_state1, tmp_15_cast_fu_1021_p1, tmp_17_cast_fu_1070_p1, ap_CS_fsm_state2, tmp_19_cast_fu_1118_p1, ap_CS_fsm_state3, tmp_21_cast_fu_1166_p1, ap_CS_fsm_state4, tmp_23_cast_fu_1219_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 <= tmp_23_cast_fu_1219_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 <= tmp_21_cast_fu_1166_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 <= tmp_19_cast_fu_1118_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 <= tmp_17_cast_fu_1070_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 <= tmp_15_cast_fu_1021_p1(9 - 1 downto 0);
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1_assign_proc : process(ap_CS_fsm_state1, tmp_16_cast_fu_1036_p1, ap_CS_fsm_state2, tmp_18_cast_fu_1084_p1, ap_CS_fsm_state3, tmp_20_cast_fu_1132_p1, ap_CS_fsm_state4, tmp_22_cast_fu_1180_p1, ap_CS_fsm_state5, tmp_24_cast_fu_1233_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 <= tmp_24_cast_fu_1233_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 <= tmp_22_cast_fu_1180_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 <= tmp_20_cast_fu_1132_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 <= tmp_18_cast_fu_1084_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 <= tmp_16_cast_fu_1036_p1(9 - 1 downto 0);
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce1 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, p_read32_cast_fu_976_p1, p_read34_cast_fu_1050_p1, p_read36_cast_fu_1098_p1, p_read38_cast_fu_1146_p1, p_read40_cast_fu_1194_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 <= p_read40_cast_fu_1194_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 <= p_read38_cast_fu_1146_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 <= p_read36_cast_fu_1098_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 <= p_read34_cast_fu_1050_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 <= p_read32_cast_fu_976_p1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, p_read33_cast_fu_971_p1, p_read35_cast_fu_1045_p1, p_read37_cast_fu_1093_p1, p_read39_cast_fu_1141_p1, p_read41_cast_fu_1189_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 <= p_read41_cast_fu_1189_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 <= p_read39_cast_fu_1141_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 <= p_read37_cast_fu_1093_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 <= p_read35_cast_fu_1045_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 <= p_read33_cast_fu_971_p1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we1 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_stubId_we1 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0_assign_proc : process(ap_CS_fsm_state1, tmp_15_cast_fu_1021_p1, tmp_17_cast_fu_1070_p1, ap_CS_fsm_state2, tmp_19_cast_fu_1118_p1, ap_CS_fsm_state3, tmp_21_cast_fu_1166_p1, ap_CS_fsm_state4, tmp_23_cast_fu_1219_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 <= tmp_23_cast_fu_1219_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 <= tmp_21_cast_fu_1166_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 <= tmp_19_cast_fu_1118_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 <= tmp_17_cast_fu_1070_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 <= tmp_15_cast_fu_1021_p1(9 - 1 downto 0);
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1_assign_proc : process(ap_CS_fsm_state1, tmp_16_cast_fu_1036_p1, ap_CS_fsm_state2, tmp_18_cast_fu_1084_p1, ap_CS_fsm_state3, tmp_20_cast_fu_1132_p1, ap_CS_fsm_state4, tmp_22_cast_fu_1180_p1, ap_CS_fsm_state5, tmp_24_cast_fu_1233_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 <= tmp_24_cast_fu_1233_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 <= tmp_22_cast_fu_1180_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 <= tmp_20_cast_fu_1132_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 <= tmp_18_cast_fu_1084_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 <= tmp_16_cast_fu_1036_p1(9 - 1 downto 0);
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce1 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0_assign_proc : process(ap_CS_fsm_state1, p_read12, p_read14, p_read16, p_read18, p_read20, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 <= p_read20;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 <= p_read18;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 <= p_read16;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 <= p_read14;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 <= p_read12;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1_assign_proc : process(ap_CS_fsm_state1, p_read13, p_read15, p_read17, p_read19, p_read21, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 <= p_read21;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 <= p_read19;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 <= p_read17;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 <= p_read15;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 <= p_read13;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we1 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_data_z_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_address0 <= tmp_fu_1209_p1(5 - 1 downto 0);

    mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_ce0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_d0 <= ap_const_lv32_0;

    mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_we0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_we0 <= ap_const_logic_1;
        else 
            mapHLS_unsigned_int_arrayHLS_residData_data_second_size_s_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_read22_cast_fu_986_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read22),32));
    p_read23_cast_fu_981_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read23),32));
    p_read24_cast_fu_1060_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read24),32));
    p_read25_cast_fu_1055_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read25),32));
    p_read26_cast_fu_1108_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read26),32));
    p_read27_cast_fu_1103_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read27),32));
    p_read28_cast_fu_1156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read28),32));
    p_read29_cast_fu_1151_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read29),32));
    p_read30_cast_fu_1204_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read30),32));
    p_read31_cast_fu_1199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read31),32));
    p_read32_cast_fu_976_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read32),32));
    p_read33_cast_fu_971_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read33),32));
    p_read34_cast_fu_1050_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read34),32));
    p_read35_cast_fu_1045_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read35),32));
    p_read36_cast_fu_1098_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read36),32));
    p_read37_cast_fu_1093_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read37),32));
    p_read38_cast_fu_1146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read38),32));
    p_read39_cast_fu_1141_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read39),32));
    p_read40_cast_fu_1194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read40),32));
    p_read41_cast_fu_1189_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_read41),32));
    p_shl1_cast_fu_1007_p3 <= (tmp_4_fu_1003_p1 & ap_const_lv1_0);
    p_shl_cast_fu_995_p3 <= (tmp_3_fu_991_p1 & ap_const_lv3_0);
    tmp_12_fu_1030_p2 <= (tmp_s_fu_1015_p2 or ap_const_lv10_1);
    tmp_13_fu_1065_p2 <= std_logic_vector(unsigned(ap_const_lv10_2) + unsigned(tmp_s_reg_1253));
    tmp_14_fu_1079_p2 <= std_logic_vector(unsigned(ap_const_lv10_3) + unsigned(tmp_s_reg_1253));
    tmp_15_cast_fu_1021_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_1015_p2),64));
    tmp_15_fu_1113_p2 <= std_logic_vector(unsigned(ap_const_lv10_4) + unsigned(tmp_s_reg_1253));
    tmp_16_cast_fu_1036_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_1030_p2),64));
    tmp_16_fu_1127_p2 <= std_logic_vector(unsigned(ap_const_lv10_5) + unsigned(tmp_s_reg_1253));
        tmp_17_cast_fu_1070_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_13_fu_1065_p2),64));

    tmp_17_fu_1161_p2 <= std_logic_vector(unsigned(ap_const_lv10_6) + unsigned(tmp_s_reg_1253));
        tmp_18_cast_fu_1084_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_14_fu_1079_p2),64));

    tmp_18_fu_1175_p2 <= std_logic_vector(unsigned(ap_const_lv10_7) + unsigned(tmp_s_reg_1253));
        tmp_19_cast_fu_1118_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_15_fu_1113_p2),64));

    tmp_19_fu_1214_p2 <= std_logic_vector(unsigned(ap_const_lv10_8) + unsigned(tmp_s_reg_1253));
        tmp_20_cast_fu_1132_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_fu_1127_p2),64));

    tmp_20_fu_1228_p2 <= std_logic_vector(unsigned(ap_const_lv10_9) + unsigned(tmp_s_reg_1253));
        tmp_21_cast_fu_1166_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_fu_1161_p2),64));

        tmp_22_cast_fu_1180_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_18_fu_1175_p2),64));

        tmp_23_cast_fu_1219_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_19_fu_1214_p2),64));

        tmp_24_cast_fu_1233_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_20_fu_1228_p2),64));

    tmp_3_fu_991_p1 <= mapHLS_unsigned_int_arrayHLS_residData_size_read(7 - 1 downto 0);
    tmp_4_fu_1003_p1 <= mapHLS_unsigned_int_arrayHLS_residData_size_read(9 - 1 downto 0);
    tmp_fu_1209_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mapHLS_unsigned_int_arrayHLS_residData_size_read),64));
    tmp_s_fu_1015_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_995_p3) + unsigned(p_shl1_cast_fu_1007_p3));
end behav;
